server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.192.194:51011/msa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dankan123456
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true
  redis:
    host: 13.124.192.194
    port: 59013
  cache:
    type: redis

cloud:
  aws:
    s3:
      bucket: dankan-images
    credentials:
      accessKey: AKIAUVIBHU2ZYFD76VOE
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
sns:
  kakao:
    key: 00c48270395b6a27deb3c5a044c1407f
    url: http://localhost:8080/login/kakao/token

sms:
  key: NCSAW8M8DY0K0BIJ
  secret: VNOCKLFUD236WQEDSQIICSVADBRZBLCJ
  phoneNumber: 010-9210-2745

mail:
  id: dankan2023@naver.com
  password: ekszks0617!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jwt:
  secret: aKDYhaH2zGcfYNttnes8zfgldpkynLqn+waoAfmn2J5diiBtQNJlzVp0PpB5JHZ2S/7pzH24wvmSzvev65c89bf8YYE+4S8dNOY2bEjniNgQDF6SZBrX/jW+h4uZsEZCYefPPOMh9zZYmKoXU5x5OnVZJRuOPym26szedZv3hE7jOm7JOK90MIdpuC7SMcikjcPAhCX0uavV/kAOgxSeRR8KzSEqpRqrg8J33KLr90FjpIROlhxQPqMFcr5T8s9sr9sIktK1w0Tvyj84UEGMXLYSzTMnR63x8qroIryHDlpPfq+J3i8JDYYkGEi3C63Ro/Ocp4gu8d5jsfOCRuGsKg==
